# -*- coding: utf-8 -*-
"""APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1FpezcQiRyxyrI1KqJk1frBvb-e_xcq
"""

import os, re, uuid, datetime
from typing import TypedDict, List, Optional
import streamlit as st
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver

#PAGE CONFIG
st.set_page_config(
    page_title="ShopMax Support",
    page_icon="S",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.sidebar.empty()

st.markdown(
    """
    <style>
    [data-testid="stSidebar"][aria-expanded="false"] {
        display: block !important;
        width: 300px !important;
    }
    </style>
    """,
    unsafe_allow_html=True
)
#CSS + JS
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,500;9..40,600&display=swap');

#Design Tokens
:root {
    --bg-base:        #18230F;
    --bg-sidebar:     #2F3E33;
    --bg-sidebar-hov: #2A3630;
    --bg-input:       #1A2812;

    --user-bubble:    #2C3E5A;
    --user-bdr:       #3A5070;
    --bot-bubble:     #D58A94;
    --bot-bdr:        #E1AD9D;

    --accent:         #91A6FF;
    --accent-glow:    rgba(145,166,255,0.22);
    --assistant:      #D58A94;

    --text-primary:   #FFFFFF;
    --text-muted:     #7A9070;
    --sb-text:        #FEFAE0;
    --sb-muted:       #B8C4A8;

    --success:        #6BCB77;
    --border:         rgba(145,166,255,0.10);
    --border-strong:  rgba(145,166,255,0.20);
    --shadow:         0 4px 16px rgba(0,0,0,0.40);

    --r-sm: 6px;
    --r-lg: 18px;
    --ease: 160ms ease;
}

#Global
body {
    background-color: var(--bg-base);
}
.block-container {
    padding-top: 0.5rem !important;
    padding-bottom: 0rem !important;
    max-width: 100% !important;
    font-family: 'DM Sans', sans-serif !important;
    color: var(--text-primary) !important;
}

#Scrollbar
::-webkit-scrollbar { width:5px; height:5px; }
::-webkit-scrollbar-track { background:var(--bg-base); }
::-webkit-scrollbar-thumb { background:var(--border-strong); border-radius:99px; }
::-webkit-scrollbar-thumb:hover { background:var(--accent); }

#Hide Streamlit chrome
#MainMenu, footer { visibility:hidden !important; }
header { visibility:hidden !important; }
[data-testid="stToolbar"]  { visibility: visible !important; }
[data-testid="stDecoration"]{ display:none !important; }

#SIDEBAR
[data-testid="stSidebar"] {
    background-color: var(--bg-sidebar) !important;
    border-right: 1px solid rgba(145,166,255,0.08) !important;
    box-shadow: 4px 0 24px rgba(0,0,0,0.30) !important;
    width: 300px !important;
    flex-shrink: 0 !important;
}
[data-testid="stSidebar"] > div:first-child {
    padding: 1.25rem 0.85rem 2rem !important;
}
section[data-testid="stSidebar"],
section[data-testid="stSidebar"] * {
    color: var(--sb-text) !important;
}

#Brand
.sb-brand {
    display:flex; align-items:center; gap:10px; margin-bottom:1.25rem;
}
.sb-logo {
    width:38px; height:38px; flex-shrink:0;
    background: linear-gradient(135deg,#91A6FF,#6B8EFF);
    border-radius:10px;
    display:flex; align-items:center; justify-content:center;
    box-shadow:0 4px 12px rgba(145,166,255,0.30);
    font-size:22px; line-height:1;
}
.sb-title {
    font-family:'DM Serif Display',serif !important;
    font-size:1.3rem; letter-spacing:-0.02em; line-height:1.1;
}
.sb-subtitle {
    font-size:0.65rem; letter-spacing:0.07em;
    text-transform:uppercase; color:var(--sb-muted) !important;
    margin-top:2px;
}

#Section labels
.sb-label {
    display:block;
    font-size:0.60rem !important; font-weight:700 !important;
    letter-spacing:0.14em !important; text-transform:uppercase !important;
    color:var(--text-muted) !important;
    margin: 1.1rem 0 0.45rem 2px !important;
}

#Search
section[data-testid="stSidebar"] [data-testid="stTextInput"] input {
    background-color: rgba(0,0,0,0.28) !important;
    border: 1px solid var(--border-strong) !important;
    border-radius: var(--r-sm) !important;
    color: var(--sb-text) !important;
    font-family:'DM Sans',sans-serif !important;
    font-size:0.82rem !important;
}
section[data-testid="stSidebar"] [data-testid="stTextInput"] input:focus {
    border-color:var(--accent) !important;
    box-shadow:0 0 0 3px var(--accent-glow) !important;
    outline:none !important;
}
section[data-testid="stSidebar"] [data-testid="stTextInput"] input::placeholder {
    color:var(--text-muted) !important;
}

#All sidebar buttons
button[data-testid="collapsedControl"] {
    display: flex !important;
    visibility: visible !important;
    opacity: 1 !important;
    z-index: 9999 !important;
}
section[data-testid="stSidebar"] .stButton > button {
    background-color: transparent !important;
    color: var(--sb-muted) !important;
    border: 1px solid var(--border) !important;
    border-radius: var(--r-sm) !important;
    padding: 0.38rem 0.75rem !important;
    font-size: 0.79rem !important;
    font-family:'DM Sans',sans-serif !important;
    width: 100% !important;
    text-align: left !important;
    margin-bottom: 0.18rem !important;
    transition: all var(--ease) !important;
}
section[data-testid="stSidebar"] .stButton > button:hover {
    background-color: var(--bg-sidebar-hov) !important;
    border-color: var(--accent) !important;
    color: var(--sb-text) !important;
    transform: translateX(3px) !important;
    box-shadow: 0 2px 8px rgba(0,0,0,0.20) !important;
}

#Clear button
section[data-testid="stSidebar"] .stButton:last-of-type > button {
    background-color: rgba(213,138,148,0.07) !important;
    border-color: rgba(213,138,148,0.30) !important;
    color: var(--assistant) !important;
}
section[data-testid="stSidebar"] .stButton:last-of-type > button:hover {
    background-color: rgba(213,138,148,0.16) !important;
    border-color: var(--assistant) !important;
    color: #F0A8B0 !important;
    transform: none !important;
}

#Expanders

section[data-testid="stSidebar"] [data-testid="stExpander"] {
    background-color: rgba(0,0,0,0.15) !important;
    border: 1px solid var(--border) !important;
    border-radius: var(--r-sm) !important;
    margin-bottom:0.32rem !important;
    overflow:hidden !important;
}
section[data-testid="stSidebar"] [data-testid="stExpander"] summary {
    color: var(--sb-muted) !important;
    font-size:0.8rem !important; font-weight:500 !important;
    padding:0.48rem 0.75rem !important;
}
section[data-testid="stSidebar"] [data-testid="stExpander"] summary:hover {
    color:var(--sb-text) !important;
}
section[data-testid="stSidebar"] hr {
    border-color:rgba(145,166,255,0.08) !important;
    margin:0.75rem 0 !important;
}

#MAIN HEADER
.main-header {
    display:flex; align-items:center; justify-content:space-between;
    padding-bottom:0.85rem;
    border-bottom:1px solid var(--border);
    margin-bottom:0.6rem;
}
.main-title {
    font-family:'DM Serif Display',serif;
    font-size:1.9rem; letter-spacing:-0.04em; line-height:1;
    background:linear-gradient(130deg,#FFFFFF 0%,var(--accent) 100%);
    -webkit-background-clip:text; -webkit-text-fill-color:transparent;
    background-clip:text;
}
.main-subtitle {
    color:var(--text-muted); font-size:0.80rem;
    margin-top:0.3rem;
}
.status-pill {
    display:flex; align-items:center; gap:6px;
    background:rgba(107,203,119,0.10);
    border:1px solid rgba(107,203,119,0.28);
    border-radius:99px; padding:4px 12px;
    font-size:0.70rem; font-weight:700;
    color:var(--success); letter-spacing:0.07em;
    white-space:nowrap;
}
.status-dot {
    width:6px; height:6px;
    background:var(--success); border-radius:50%;
    animation:pdot 2s ease-in-out infinite;
}
@keyframes pdot {
    0%,100%{ opacity:1; transform:scale(1); }
    50%    { opacity:0.35; transform:scale(0.75); }
}

#Info chips
.info-strip { display:flex; gap:8px; flex-wrap:wrap; margin-bottom:1rem; }
.info-chip {
    display:flex; align-items:center; gap:4px;
    background:rgba(145,166,255,0.06);
    border:1px solid var(--border-strong);
    border-radius:99px; padding:3px 10px;
    font-size:0.69rem; color:var(--text-muted);
}
.info-chip b { color:var(--accent); font-weight:500; }

#AVATAR

#Avatar background colours
[data-testid="stChatMessage"] [data-testid="chatAvatarIcon-user"] {
    background: linear-gradient(135deg,#5B78CC,#91A6FF) !important;
    box-shadow:0 2px 8px rgba(145,166,255,0.30) !important;
}
[data-testid="stChatMessage"] [data-testid="chatAvatarIcon-assistant"] {
    background: linear-gradient(135deg,#8A4550,#D58A94) !important;
    box-shadow:0 2px 8px rgba(213,138,148,0.30) !important;
}

#CHAT MESSAGES — BUBBLES

#Chat row layout
.chat-row {
    display: flex;
    width: 100%;
    margin-bottom: 0.85rem;
}

#Alignment
.chat-row.user {
    justify-content: flex-end;
}
.chat-row.bot {
    justify-content: flex-start;
}

#Bubble base
.chat-bubble {
    background: #1E2E18 !important;
    max-width: 70%;
    padding: 0.78rem 1.1rem;
    border-radius: 15px;
    font-size: 0.88rem;
    line-height: 1.6;
    box-shadow: 0 4px 16px rgba(0,0,0,0.40);
}

#User bubble
.chat-row.user .chat-bubble {
    background: linear-gradient(135deg, #2C3E5A, #243350) !important;
    border: 1px solid #3A5070;
    border-radius: 15px 15px 0 15px;
}

#Bot bubble
.chat-row.bot .chat-bubble {
    background: linear-gradient(135deg, #D58A94, #E1AD9D) !important;
    border: 1px solid #2E4228;
    border-radius: 15px 15px 15px 0;
}

#Typing indicator
.typing-wrap {
    display:flex; align-items:center; gap:5px;
    padding:0.55rem 0.9rem;
    background: linear-gradient(135deg, #1E2E18, #182415);
    border:1px solid #2E4228;
    border-radius:15px 15px 15px 0;
    width:fit-content; margin-bottom:0.75rem;
    box-shadow:var(--shadow);
}
.tdot {
    width:7px; height:7px;
    background:var(--assistant); border-radius:50%;
    animation:tdbounce 1.25s ease-in-out infinite;
}
.tdot:nth-child(2){ animation-delay:.22s; }
.tdot:nth-child(3){ animation-delay:.44s; }
@keyframes tdbounce {
    0%,80%,100%{ transform:translateY(0); opacity:0.4; }
    40%        { transform:translateY(-6px); opacity:1; }
}

#CHAT INPUT
[data-testid="stChatInput"] {
    border-radius: 12px !important;
}
[data-testid="stChatInput"] textarea {
    background-color: transparent !important;
    color: var(--text-primary) !important;
    font-family:'DM Sans',sans-serif !important;
    font-size:0.9rem !important;
    caret-color:var(--accent) !important;
}
[data-testid="stChatInput"] textarea::placeholder {
    color:var(--text-muted) !important; font-style:italic;
}
[data-testid="stChatInput"] button {
    background: linear-gradient(135deg,var(--accent),#6B8EFF) !important;
    border-radius: 10px !important;
    transition: transform var(--ease), box-shadow var(--ease) !important;
}
[data-testid="stChatInput"] button:hover {
    transform:scale(1.08) !important;
    box-shadow:0 4px 14px var(--accent-glow) !important;
}

/* Prevent layout shift when sidebar loads */
section.main > div {
    padding-left: 0rem !important;
}
</style>
""", unsafe_allow_html=True)


#STATE
class FinState(TypedDict):
    question:     str
    messages:     List[dict]
    route:        str
    retrieved:    str
    sources:      List[str]
    tool_result:  str
    answer:       str
    faithfulness: float
    eval_retries: int
    user_name:    Optional[str]


#KNOWLEDGE BASE
DOCUMENTS = [
    {
        'id':'doc_001','category':'Electronics > Audio','topic':'Wireless Headphones',
        'sku':'WH-300','price':1999,'discount':'10%','stock_status':'In Stock',
        'text':(
            'The ShopMax Wireless Headphones (Model WH-300) use Bluetooth 5.3 for a stable, '
            'low-latency connection up to 10 metres. Battery life is 20 hours on a single charge, '
            'with a 2-hour fast-charge via USB-C. The headphones include active noise cancellation (ANC), '
            'a built-in microphone for calls, and 40mm drivers for rich bass. Weight is 250g. '
            'They are foldable and come with a hard carrying case. Available colours: Black, White, Navy Blue. '
            'Price: Rs 1,999. Currently available at a 10% discount. Covered by a 1-year manufacturer warranty '
            'against hardware defects. Compatible with iOS, Android, Windows, and macOS. Not waterproof.'
        )
    },
    {
        'id':'doc_002','category':'Electronics > Wearables','topic':'Smart Watch',
        'sku':'SW-200','price':2999,'discount':'10%','stock_status':'In Stock',
        'text':(
            'The ShopMax Smart Watch (Model SW-200) tracks steps, calories, sleep, heart rate, '
            'and blood oxygen (SpO2). It has a 1.4-inch AMOLED display with always-on mode. '
            'Battery life is 7 days in normal mode, 3 days with always-on display enabled. '
            'It is IP68 waterproof — safe for swimming up to 50 metres. Compatible with iOS 12+ and Android 8+. '
            'Includes 20+ workout modes. Built-in GPS for outdoor runs. '
            'Supports notifications for calls, SMS, and apps. Strap is interchangeable (22mm standard). '
            'Price: Rs 2,999. Currently available at a 10% discount. 1-year warranty.'
        )
    },
    {
        'id':'doc_003','category':'Electronics > Accessories','topic':'Mechanical Keyboard',
        'sku':'KB-75','price':3499,'discount':'10%','stock_status':'In Stock',
        'text':(
            'The ShopMax Mechanical Keyboard (Model KB-75) is a tenkeyless (TKL) wired keyboard with '
            'Cherry MX Red switches — linear, quiet, and ideal for both typing and gaming. '
            'It has per-key RGB backlighting with 15 preset lighting modes. Aluminium top plate and '
            'PBT double-shot keycaps. N-key rollover (NKRO). USB-A braided cable (1.8m). '
            'Layout: US ANSI. Compatible with Windows 10/11 and macOS. No driver required. '
            'Price: Rs 3,499. Currently available at a 10% discount. 2-year warranty.'
        )
    },
    {
        'id':'doc_004','category':'Electronics > Audio','topic':'Portable Bluetooth Speaker',
        'sku':'BS-50','price':2499,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax Blast Speaker (Model BS-50) delivers 20W stereo sound with dual 10W drivers '
            'and a passive radiator for deep bass. Battery lasts 12 hours at 70% volume. '
            'IPX7 waterproof — fully submersible up to 1 metre for 30 minutes. '
            'Bluetooth 5.0 range up to 15 metres. Supports wired AUX input (3.5mm). '
            'Built-in microphone for speakerphone calls. Charges in 3 hours via USB-C. '
            'Dimensions: 18cm x 7cm. Weight: 600g. Colours: Red, Black, Forest Green. '
            'Price: Rs 2,499. 1-year warranty.'
        )
    },
    {
        'id':'doc_005','category':'Electronics > Charging','topic':'USB-C Fast Charger',
        'sku':'FC-65','price':1299,'discount':'5%','stock_status':'In Stock',
        'text':(
            'The ShopMax 65W USB-C GaN Charger (Model FC-65) supports USB Power Delivery 3.0. '
            'Two ports: USB-C (65W max) and USB-A (18W max, Quick Charge 3.0). '
            'GaN technology makes it 40% smaller than traditional chargers. '
            'Charges an iPhone 15 to 50% in 30 minutes. MacBook Air in under 2 hours. '
            'Universal voltage (100-240V). Cable not included. Price: Rs 1,299. 1-year warranty. Colour: White.'
        )
    },
    {
        'id':'doc_006','category':'Accessories','topic':'Laptop Stand',
        'sku':'LS-20','price':899,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax ErgoRise Laptop Stand (Model LS-20) is anodised aluminium, supports 10-16 inch '
            'laptops up to 10kg. Height adjustable across 6 levels (10-20cm), angle 15-45 degrees. '
            'Folds flat — packed size 28cm x 22cm x 1.5cm, weight 500g. Silicone pads grip desk. '
            'No USB hub. Compatible with all brands. Price: Rs 899. 1-year warranty. Silver or Space Grey.'
        )
    },
    {
        'id':'doc_013','category':'Electronics > Power','topic':'Power Bank',
        'sku':'PB-20000','price':1499,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax Power Bank (Model PB-20000) has 20,000mAh capacity. '
            '18W fast charging via USB-C PD and QC 3.0. 2 USB-A and 1 USB-C port. '
            'Charges a smartphone 4-5 times. Fully recharges in 6-7 hours with 18W charger. '
            'Protections against overcharge, over-discharge, and short circuit. '
            'Weight: 450g. Price: Rs 1,499. 1-year warranty. Colour: Black.'
        )
    },
    {
        'id':'doc_014','category':'Electronics > Audio','topic':'True Wireless Earbuds',
        'sku':'TWS-100','price':1799,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax True Wireless Earbuds (Model TWS-100) feature Bluetooth 5.2 with auto-pairing '
            'and touch controls. 5 hours per charge, 20 extra hours from the case. '
            'ENC for clearer calls. IPX5 water resistance. USB-C fast charging (10 min = 1 hr). '
            '3 sizes of ear tips included. Price: Rs 1,799. 1-year warranty.'
        )
    },
    {
        'id':'doc_015','category':'Electronics > Gaming','topic':'Gaming Mouse',
        'sku':'GM-80','price':1299,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax Gaming Mouse (Model GM-80) has a 16,000 DPI optical sensor, '
            '6 programmable buttons, RGB lighting, and 1000Hz polling rate. '
            'Right-handed ergonomic design. USB-A braided cable (1.6m). Windows and macOS compatible. '
            'Software required for customization. Weight: 120g. Price: Rs 1,299. 1-year warranty.'
        )
    },
    {
        'id':'doc_016','category':'Electronics > Storage','topic':'External SSD',
        'sku':'SSD-1TB','price':6999,'discount':None,'stock_status':'In Stock',
        'text':(
            'The ShopMax External SSD (Model SSD-1TB) offers 1TB storage, read up to 1050 MB/s, '
            'write up to 1000 MB/s. USB 3.2 Gen 2 / USB-C. Aluminium, shock-resistant. '
            'Compatible with Windows, macOS, Android OTG, and gaming consoles. '
            'Includes USB-C to C and USB-C to A cables. Weight: 90g. Price: Rs 6,999. 3-year warranty.'
        )
    },
    {
        'id':'doc_007','category':'Policy','topic':'Return Policy',
        'text':(
            'Customers may return any product within 7 days of delivery for a full refund, '
            'provided the item is unused, in its original packaging, with all accessories. '
            'Initiate via ShopMax account > Orders > Return. Pickup arranged in 1-2 business days, free. '
            'Not eligible: misused items, missing parts, returns after 7 days, opened software, digital downloads. '
            'Refunds processed within 5-7 business days after receipt and verification.'
        )
    },
    {
        'id':'doc_008','category':'Policy','topic':'Shipping Policy',
        'text':(
            'ShopMax ships across India. Standard delivery 3-5 business days; free above Rs 499, else Rs 49. '
            'Express delivery (1-2 days) costs Rs 99. Same-day delivery (Rs 149) available in Bangalore, '
            'Mumbai, Delhi, Hyderabad, Chennai for orders before 11am. '
            'Dispatched Mon-Sat. Tracking link sent via SMS and email. International shipping unavailable.'
        )
    },
    {
        'id':'doc_009','category':'Policy','topic':'Refund Policy',
        'text':(
            'Refunds processed within 5-7 business days after warehouse verification. '
            'Credit/debit card refunds to original card. UPI/net banking to original account. '
            'COD orders refunded via bank transfer — provide account number and IFSC. '
            'ShopMax Wallet refunds within 24 hours. Email confirmation sent when initiated. '
            'Contact support with order ID if refund not received in 7 business days.'
        )
    },
    {
        'id':'doc_010','category':'Policy','topic':'Warranty Policy',
        'text':(
            'All ShopMax products include a manufacturer warranty. Most: 1 year; KB-75: 2 years. '
            'Claims: contact support@shopmax.in or 1800-123-4567 within the warranty period. '
            'Covers: DOA units, manufacturing defects, component failure under normal use. '
            'Does NOT cover: physical damage, water damage (non-waterproof products), '
            'incorrect voltage damage, unauthorised repair. Proof of purchase required. '
            'Approved claims: free repair or replacement.'
        )
    },
    {
        'id':'doc_011','category':'Policy','topic':'Payment Methods',
        'text':(
            'ShopMax accepts: Credit cards (Visa, Mastercard, Amex, RuPay), debit cards, '
            'UPI (GPay, PhonePe, Paytm, BHIM), net banking (50+ banks), '
            'Cash on Delivery (up to Rs 10,000), ShopMax Wallet. '
            'EMI on orders above Rs 3,000 via eligible credit cards (3/6/9/12 months). '
            'BNPL via ZestMoney and LazyPay. 256-bit SSL encryption. Prices inclusive of 18% GST.'
        )
    },
    {
        'id':'doc_012','category':'Policy','topic':'Order Tracking and Cancellation',
        'text':(
            'Confirmation email/SMS sent immediately after order. Tracking link from courier '
            '(Delhivery, Ekart, BlueDart) shared after dispatch. Track at shopmax.in/track or via app. '
            'Cancel free within 12 hours if not dispatched: My Orders > Cancel Order. '
            'Dispatched orders cannot be cancelled — request a return after delivery. '
            'Pre-dispatch cancellation refunds processed within 24 hours. '
            'Issues: support@shopmax.in or 1800-123-4567.'
        )
    },
    {
        'id':'doc_017','topic':'Exchange Policy',
        'text':(
            'ShopMax allows exchanges within 7 days of delivery for defective or damaged-on-arrival items. '
            'Request via account > Orders. Replacement shipped after pickup and inspection. '
            'Subject to stock availability; full refund issued if unavailable. '
            'Return with original packaging and all accessories.'
        )
    },
    {
        'id':'doc_018','topic':'Account and Security Policy',
        'text':(
            'Customers are responsible for keeping ShopMax account credentials confidential. '
            'ShopMax uses 256-bit SSL encryption. Do not share OTPs or passwords. '
            'Report suspicious activity to support@shopmax.in. '
            'ShopMax is not liable for unauthorised access due to user negligence.'
        )
    },
    {
        'id':'doc_019','topic':'Privacy Policy',
        'text':(
            'ShopMax collects name, contact details, and payment info to process orders and improve services. '
            'Data stored securely, not sold to third parties. '
            'Shared with logistics partners for delivery. Customers can request data deletion via support. '
            'Cookies used to enhance browsing and personalise recommendations.'
        )
    },
    {
        'id':'doc_020','topic':'Customer Support Policy',
        'text':(
            'ShopMax customer support: Monday-Saturday, 9am-7pm IST. '
            'Email: support@shopmax.in | Phone: 1800-123-4567 (toll-free) | Live chat on website/app. '
            'Response within 24 hours for email; immediate for calls and chat. '
            'Assists with orders, returns, refunds, warranty, and technical issues.'
        )
    },
]


#VECTOR DB]
@st.cache_resource(show_spinner="Loading knowledge base...")
def load_vectordb():
    emb   = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")
    texts = [d["text"] for d in DOCUMENTS]
    metas = [{"topic": d["topic"], "id": d["id"]}
             for d in DOCUMENTS]
    return Chroma.from_texts(texts=texts, embedding=emb, metadatas=metas)


#LLM
def get_llm(temperature: float = 0.1):
    return ChatGroq(
        model='llama-3.1-8b-instant',
        api_key=os.environ['GROQ_API_KEY'],
        temperature=temperature,
    )


#HELPERS
def simple_rerank(query, docs):
    q = query.lower()
    scored = []
    for doc in docs:
        score = sum(1 for w in q.split() if w in doc.page_content.lower())
        if doc.metadata.get('topic', '').lower() in q:
            score += 3
        scored.append((score, doc))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [d for _, d in scored[:3]]


def discount_calculator(question: str) -> str:
    q = question.lower()


    m = re.search(r'price\s*(?:is)?\s*(\d+)\s*after\s*(\d+)\s*%', q)
    if m:
        final_price = float(m.group(1))
        pct = float(m.group(2))
        original = final_price / (1 - pct/100)
        return (
            f"If Rs {final_price:.2f} is after a {pct:.0f}% discount, "
            f"the original price was Rs {original:,.2f}."
        )

    m = re.search(r'(\d+)\s*%\s*(?:on|of)\s*rs?\s*(\d+)', q)
    if m:
        pct = float(m.group(1))
        price = float(m.group(2))
        disc = price * pct / 100
        return (
            f"A {pct:.0f}% discount on Rs {price:,.2f} saves Rs {disc:,.2f}. "
            f"Final price: Rs {price-disc:,.2f}."
        )

    return "Please specify like '10% on Rs 1000' or 'price is 900 after 10% discount'."


#GRAPH NODES
def memory_node(state: FinState) -> dict:
    msgs = (state.get('messages') or []) + \
        [{'role':'user','content':state['question']}]
    user_name = state.get('user_name')
    m = re.search(r'my name is ([A-Za-z]+)', state['question'], re.IGNORECASE)
    if m:
        user_name = m.group(1).capitalize()
    return {**state, 'messages': msgs[-6:], 'user_name': user_name}


def router_node(state: FinState) -> dict:
    llm = get_llm()
    prompt = (
        "You are a routing agent for an e-commerce support bot.\n"
        "Classify into ONE of: retrieve | tool | skip\n"
        "- retrieve: products, returns, shipping, refunds, warranty, payment, tracking, cancellation\n"
        "- tool: date, time, discount calculation\n"
        "- skip: greetings, small talk, off-topic\n"
        "Reply with ONE word only.\n\n"
        f"Question: {state['question']}\nRoute:"
    )
    raw = llm.invoke(prompt).content.strip().lower().split()[0]
    return {**state, 'route': raw if raw in ('retrieve', 'tool', 'skip') else 'retrieve'}


def retrieval_node(state: FinState) -> dict:
    db     = load_vectordb()
    docs   = db.similarity_search(state['question'], k=5)
    ranked = simple_rerank(state['question'], docs)
    parts, sources = [], []
    for d in ranked:
        topic = d.metadata.get('topic', 'Info')
        parts.append(f"[{topic}]\n{d.page_content}")
        sources.append(topic)
    return {**state, 'retrieved': '\n\n'.join(parts), 'sources': sources}


def skip_node(state: FinState) -> dict:
    return {**state, 'retrieved': '', 'sources': []}


def tool_node(state: FinState) -> dict:
    q = state['question']
    if re.search(r'date|time|today', q, re.IGNORECASE):
        now    = datetime.datetime.now()
        result = (f"Today is {now.strftime('%A, %d %B %Y')}. "
                  f"Current time is {now.strftime('%I:%M %p')} IST.")
        src    = ['datetime']
    elif re.search(r'discount|%|percent|off', q, re.IGNORECASE):
        result = discount_calculator(q)
        src    = ['discount_calculator']
    else:
        result = "I'm not sure which tool to use for that request."
        src    = []
    return {**state, 'tool_result': result, 'retrieved': '', 'sources': src}


def answer_node(state: FinState) -> dict:
    llm = get_llm(temperature=0.1)

    retrieved   = state.get('retrieved', '').strip()
    tool_result = state.get('tool_result', '').strip()
    user_name   = state.get('user_name', '')
    retries     = state.get('eval_retries', 0)

    name_part = f"The customer's name is {user_name}. Address them naturally.\n" if user_name else ""

    retry_instruction = ""
    if retries > 0:
        retry_instruction = (
            f"\nIMPORTANT: This is retry attempt {retries}. "
            "Your previous answer was incorrect or not grounded in the provided information. "
            "You MUST strictly follow all rules and not hallucinate.\n"
        )

    context_blocks = []
    if retrieved:
        context_blocks.append(f"[KNOWLEDGE BASE]\n{retrieved}")
    if tool_result:
        context_blocks.append(f"[TOOL RESULT]\n{tool_result}")

    context_section = "\n\n".join(context_blocks)

    prompt = f"""You are an intelligent customer support assistant for ShopMax (an e-commerce platform).

{name_part}
{retry_instruction}

SYSTEM ROLE:

You must correctly handle THREE types of user requests:

1. CHITCHAT
   - Greetings, small talk, casual conversation
   - Respond naturally, warmly, and briefly

2. TOOL-BASED
   - Calculations (discounts), date/time, utility queries
   - If a TOOL RESULT is provided → you MUST use it directly
   - Do NOT recompute or modify tool outputs

3. KNOWLEDGE-BASED (RAG)
   - Questions about ShopMax PRODUCTS or POLICIES


KNOWLEDGE STRUCTURE:

PRODUCTS:
- Product details such as features, specifications, price, discount, compatibility, warranty

POLICIES:
- Rules such as return policy, refund timelines, shipping details, payment methods, warranty terms


STRICT GROUNDING RULES:

When answering from KNOWLEDGE BASE:

1. Use ONLY the provided context
2. Do NOT use prior knowledge
3. Do NOT guess, infer, or assume missing details
4. Do NOT combine unrelated pieces of information
5. Extract exact facts (numbers, prices, durations, limits) precisely as written
6. If the answer is NOT explicitly present, respond EXACTLY:
   "I don't have that information in my knowledge base."


TOOL PRIORITY RULE:

If TOOL RESULT is present:
- Use it directly as the answer
- Do NOT add explanations, reasoning, or extra text
- Output only the final result in a natural sentence
- Do NOT override it with knowledge base information


ANSWER STYLE RULES:

- Be concise, clear, and helpful
- Do NOT repeat the question
- Do NOT mention "context", "documents", or internal reasoning
- Do NOT use emojis
- Address the user naturally if their name is available
-Do NOT add introductory phrases like:
"I have the information you need"
"Based on the information"
"Here is the answer"

Start directly with the answer.


DECISION LOGIC:

Follow this EXACT order:

Step 1: If TOOL RESULT exists → use it
Step 2: Else if question is about PRODUCTS or POLICIES → use KNOWLEDGE BASE
Step 3: Else → treat as CHITCHAT


CONTEXT:
{context_section if context_section else "No additional context available."}


CUSTOMER QUESTION:
{state['question']}

FINAL ANSWER:
"""

    answer = llm.invoke(prompt).content.strip()

    return {**state, 'answer': answer}


def eval_node(state: FinState) -> dict:
    if not state.get('retrieved'):
        return {**state, 'faithfulness': 1.0}
    llm = get_llm()
    prompt = (
        "Rate how faithful this answer is to the context.\n"
        "1.0 = only context facts used. 0.0 = hallucinated.\n\n"
        f"Context:\n{state['retrieved']}\n\nAnswer:\n{state['answer']}\n\n"
        "Reply with a single decimal 0.0-1.0. Nothing else."
    )
    raw = llm.invoke(prompt).content.strip()
    try:
        score = min(max(float(re.findall(r'\\d+\\.?\\d*', raw)[0]), 0.0), 1.0)
    except Exception:
        score = 0.5
    return {**state, 'faithfulness': score, 'eval_retries': state.get('eval_retries', 0)+1}


def save_node(state: FinState) -> dict:
    msgs = (state.get('messages') or []) + \
        [{'role':'assistant','content':state['answer']}]
    return {**state, 'messages': msgs[-6:]}


#GRAPH
@st.cache_resource
def build_graph():
    memory = MemorySaver()
    g = StateGraph(FinState)
    for name, fn in [('memory', memory_node), ('router', router_node), ('retrieve', retrieval_node),
                     ('skip', skip_node), ('tool', tool_node), ('answer', answer_node),
                     ('eval', eval_node), ('save', save_node)]:
        g.add_node(name, fn)
    g.set_entry_point('memory')
    g.add_edge('memory', 'router')
    g.add_conditional_edges('router', lambda s: s['route'],
                            {'retrieve': 'retrieve', 'tool': 'tool', 'skip': 'skip'})
    for n in ('retrieve', 'tool', 'skip'):
        g.add_edge(n, 'answer')
    g.add_edge('answer', 'eval')
    g.add_conditional_edges('eval',
        lambda s: 'answer' if s['faithfulness'] < 0.7 and s['eval_retries'] < 2 else 'save',
        {'answer': 'answer', 'save': 'save'})
    g.add_edge('save', END)
    return g.compile(checkpointer=memory)


#SESSION STATE
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = [
        {'role':'assistant','content':'Welcome to ShopMax Support. How can I help you today?'}
    ]
if 'thread_id' not in st.session_state:
    st.session_state.thread_id = str(uuid.uuid4())
if 'trigger_query' not in st.session_state:
    st.session_state.trigger_query = None

graph = build_graph()


#  SIDEBAR
with st.sidebar:

    st.markdown("""
    <div class="sb-brand">
        <div class="sb-logo">S</div>
        <div>
            <div class="sb-title">ShopMax</div>
            <div class="sb-subtitle">Support Centre</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<span class="sb-label">Search</span>', unsafe_allow_html=True)
    search_q = st.text_input(
        "search", placeholder="Search products or policies...",
        label_visibility="collapsed", key="search_bar"
    )
    if search_q:
        st.session_state.trigger_query = search_q

    st.divider()

    st.markdown('<span class="sb-label">Quick Actions</span>', unsafe_allow_html=True)
    c1, c2 = st.columns(2)
    with c1:
        if st.button("Track Order", use_container_width=True, key="qa_track"):
            st.session_state.trigger_query = "How do I track or cancel my order?"
    with c2:
        if st.button("View Offers", use_container_width=True, key="qa_offers"):
            st.session_state.trigger_query = "Which products have a discount right now?"
    if st.button("List All Products", use_container_width=True, key="qa_list"):
        st.session_state.trigger_query = "What products does ShopMax sell?"
    if st.button("Contact Support", use_container_width=True, key="qa_contact"):
        st.session_state.trigger_query = "How can I contact customer support?"

    st.divider()

    st.markdown('<span class="sb-label">Products</span>', unsafe_allow_html=True)
    with st.expander("Audio & Wearables"):
        if st.button("Wireless Headphones (WH-300)", key="p_wh"):
            st.session_state.trigger_query = "Tell me about Wireless Headphones WH-300"
        if st.button("True Wireless Earbuds (TWS-100)", key="p_tws"):
            st.session_state.trigger_query = "Tell me about True Wireless Earbuds TWS-100"
        if st.button("Blast Speaker (BS-50)", key="p_bs"):
            st.session_state.trigger_query = "Tell me about Portable Bluetooth Speaker BS-50"
        if st.button("Smart Watch (SW-200)", key="p_sw"):
            st.session_state.trigger_query = "Features of Smart Watch SW-200"

    with st.expander("Gaming & Accessories"):
        if st.button("Mechanical Keyboard (KB-75)", key="p_kb"):
            st.session_state.trigger_query = "Specs for Mechanical Keyboard KB-75"
        if st.button("Gaming Mouse (GM-80)", key="p_gm"):
            st.session_session.trigger_query = "Tell me about Gaming Mouse GM-80"
        if st.button("Laptop Stand (LS-20)", key="p_ls"):
            st.session_state.trigger_query = "Details on ErgoRise Laptop Stand LS-20"

    with st.expander("Storage & Power"):
        if st.button("External SSD 1TB", key="p_ssd"):
            st.session_state.trigger_query = "Tell me about External SSD SSD-1TB"
        if st.button("Power Bank 20000mAh", key="p_pb"):
            st.session_state.trigger_query = "Power Bank PB-20000 capacity"
        if st.button("65W GaN Charger (FC-65)", key="p_fc"):
            st.session_state.trigger_query = "Tell me about USB-C Fast Charger FC-65"

    st.divider()

    st.markdown('<span class="sb-label">Policies</span>', unsafe_allow_html=True)
    POLICIES = [
        ("Return Policy",                 "What is the return policy?"),
        ("Shipping Policy",               "How much is shipping?"),
        ("Refund Policy",                 "How long do refunds take?"),
        ("Warranty Policy",               "What is the warranty policy?"),
        ("Payment Methods",               "What payment methods do you accept?"),
        ("Order Tracking & Cancellation", "How do I track or cancel an order?"),
        ("Exchange Policy",               "What is the exchange policy?"),
        ("Privacy Policy",                "What is the privacy policy?"),
    ]
    for label, query in POLICIES:
        if st.button(label, key=f"pol_{label}"):
            st.session_state.trigger_query = query

    st.divider()

    st.markdown('<span class="sb-label">Session</span>', unsafe_allow_html=True)
    if st.button("Clear Conversation", use_container_width=True, key="clear_btn"):
        st.session_state.chat_history = [
            {'role':'assistant','content':'Conversation cleared. How can I help you?'}
        ]
        st.session_state.thread_id = str(uuid.uuid4())
        st.rerun()


#  MAIN CHAT AREA
st.markdown("""
<div class="main-header">
    <div>
        <div class="main-title">ShopMax Support</div>
        <div class="main-subtitle">Intelligent assistance &middot; Products &middot; Policies &middot; Orders</div>
    </div>
    <div class="status-pill"><div class="status-dot"></div>LIVE</div>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div class="info-strip">
    <div class="info-chip">Mon&ndash;Sat <b>9am&ndash;7pm IST</b></div>
    <div class="info-chip">Email <b>support@shopmax.in</b></div>
    <div class="info-chip">Toll-free <b>1800-123-4567</b></div>
    <div class="info-chip">Reply <b>&lt;24h</b></div>
</div>
""", unsafe_allow_html=True)

# Render history
for msg in st.session_state.chat_history:
    role_class = "user" if msg["role"] == "user" else "bot"

    with st.chat_message(msg["role"]):
        st.markdown(
            f"""
            <div class="chat-row {role_class}">
                <div class="chat-bubble">
                    {msg["content"]}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

# Single chat_input call
user_input = st.chat_input("Ask about products, returns, shipping, or anything else...")

# Handle sidebar triggers
if st.session_state.trigger_query:
    user_input = st.session_state.trigger_query
    st.session_state.trigger_query = None

# Process
if user_input:
    with st.chat_message('user'):
        st.markdown(
            f"""
            <div class="chat-row user">
                <div class="chat-bubble">
                    {user_input}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    state = {
        'question':     user_input,
        'messages':     st.session_state.chat_history,
        'route':        '',
        'retrieved':    '',
        'sources':      [],
        'tool_result':  '',
        'answer':       '',
        'faithfulness': 1.0,
        'eval_retries': 0,
        'user_name':    None,
    }
    config = {'configurable': {'thread_id': st.session_state.thread_id}}

    with st.chat_message('assistant'):
        ph = st.empty()

        ph.markdown("""
        <div class="chat-row bot">
            <div class="chat-bubble">
                <div class="typing-wrap">
                    <div class="tdot"></div>
                    <div class="tdot"></div>
                    <div class="tdot"></div>
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

        result = graph.invoke(state, config)

        ph.markdown(
            f"""
            <div class="chat-row bot">
                <div class="chat-bubble">
                    {result['answer']}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.session_state.chat_history = result['messages']